USE ProjectManagerDB;
GO

DENY INSERT, UPDATE, DELETE ON Permissions TO PUBLIC;
GRANT SELECT ON Permissions TO PUBLIC;

DENY INSERT, UPDATE, DELETE ON Roles TO PUBLIC;
GRANT SELECT ON Roles TO PUBLIC;